set-window-option -g automatic-rename on
set-option -g set-titles on

setw -g mode-keys vi
setw -g monitor-activity on

set -g mouse on

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# vim-like pane resizing  
bind -r C-k resize-pane -U
bind -r C-j resize-pane -D
bind -r C-h resize-pane -L
bind -r C-l resize-pane -R
bind -r Tab last-window

set -sg escape-time 0
set-option repeat-time 0

# vim-like pane switching
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R 

# and now unbind keys
unbind Up
unbind Down
unbind Left
unbind Right

unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

unbind s
unbind v

bind -r s split-window -v -c "#{pane_current_path}"
bind -r v split-window -h -c "#{pane_current_path}"

# vim-like navigation
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)(g?(view|n?vim?x?)(diff)?|git)$"'
bind-key -n C-w if-shell "$is_vim" "send-keys C-w" "switch-client -Ttable1"
bind-key -r -Ttable1 'C-h' resize-pane -L
bind-key -Ttable1 'j' select-pane -D
bind-key -r -Ttable1 'C-j' resize-pane -D
bind-key -Ttable1 'k' select-pane -U
bind-key -r -Ttable1 'C-k' resize-pane -U
bind-key -Ttable1 'l' select-pane -R
bind-key -r -Ttable1 'C-l' resize-pane -R
bind-key -Ttable1 '\' select-pane -l
bind-key -Ttable1 's' split-window -v -c "#{pane_current_path}"
bind-key -Ttable1 'v' split-window -h -c "#{pane_current_path}"
bind-key -Ttable1 'c' kill-pane
bind-key -Ttable1 'n' new-window -c "#{pane_current_path}"
bind-key -Ttable1 'C-w' send-keys C-w

bind-key x kill-pane

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
